# Generated by Django 2.2.19 on 2023-07-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(help_text='укажите ID cотрудника в Telegram', verbose_name='ID cотрудника в Telegram')),
                ('full_name', models.CharField(help_text='укажите ФИО cотрудника', max_length=150, verbose_name='ФИО сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='укажите номер заказа покупателя', verbose_name='номер заказа покупателя')),
                ('item_order', models.PositiveSmallIntegerField(help_text='укажите номер позиции в заказе покупателя', verbose_name='номер позиции в заказе покупателя')),
                ('execution_time', models.PositiveSmallIntegerField(help_text='укажите время выполнения в минутах', verbose_name='время выполнения(минут)')),
                ('image', models.ImageField(help_text='добавьте фотографию', upload_to='image/', verbose_name='фотография')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='время заполнения отчета')),
                ('employee', models.ForeignKey(help_text='укажите сотрудника', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='report.Employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
                'default_related_name': 'report',
            },
        ),
    ]
