# Generated by Django 2.2.19 on 2023-07-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_related_name': 'employee', 'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(help_text='укажите сотрудника', on_delete=django.db.models.deletion.PROTECT, related_name='report', to='report.Employee', verbose_name='сотрудник'),
        ),
    ]
