# Generated by Django 2.2.19 on 2023-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20230716_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, help_text='добавьте фотографию', upload_to='image/', verbose_name='фотография'),
        ),
    ]
