# Generated by Django 4.2.3 on 2023-07-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20230716_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(help_text='укажите сотрудника', on_delete=django.db.models.deletion.PROTECT, to='report.employee', verbose_name='сотрудник'),
        ),
    ]
