# Generated by Django 4.2.3 on 2023-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, help_text='добавьте фотографию', upload_to='image/', verbose_name='фотография'),
        ),
    ]
