# Generated by Django 4.2.3 on 2023-08-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='WorkReport',
        ),
        migrations.AlterModelOptions(
            name='workreport',
            options={'default_related_name': 'work_report', 'verbose_name': 'отчет о работе', 'verbose_name_plural': 'отчеты о работе'},
        ),
        migrations.CreateModel(
            name='CleanReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='добавьте фотографию', upload_to='image/', verbose_name='фотография')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='время заполнения отчета')),
                ('employee', models.ForeignKey(help_text='укажите сотрудника', on_delete=django.db.models.deletion.PROTECT, to='report.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'отчет об уборке',
                'verbose_name_plural': 'отчеты об уборке',
                'default_related_name': 'clean_report',
            },
        ),
    ]
