# Generated by Django 4.2.3 on 2023-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='укажите имя cотрудника латиницей', max_length=150, verbose_name='ФИО сотрудника латиницей'),
        ),
    ]
